// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1aA2BEAJ0QBmLbjqtZXTKYa0B9-GKlA',
    appId: '1:955871740032:web:9166fade51a67d1164a665',
    messagingSenderId: '955871740032',
    projectId: 'drawer-57cde',
    authDomain: 'drawer-57cde.firebaseapp.com',
    databaseURL: 'https://drawer-57cde-default-rtdb.firebaseio.com',
    storageBucket: 'drawer-57cde.appspot.com',
    measurementId: 'G-620K54YXVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3xdZCoqA7i79xNLPkFOGy4hk7b2aqJGQ',
    appId: '1:955871740032:android:4ec9c95ae293bcf464a665',
    messagingSenderId: '955871740032',
    projectId: 'drawer-57cde',
    databaseURL: 'https://drawer-57cde-default-rtdb.firebaseio.com',
    storageBucket: 'drawer-57cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSkmFlT54Q7PfFbcA_glOYWCm30-0Z5Q',
    appId: '1:955871740032:ios:47cd0d76ca4e59c464a665',
    messagingSenderId: '955871740032',
    projectId: 'drawer-57cde',
    databaseURL: 'https://drawer-57cde-default-rtdb.firebaseio.com',
    storageBucket: 'drawer-57cde.appspot.com',
    iosBundleId: 'com.example.smartGrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSkmFlT54Q7PfFbcA_glOYWCm30-0Z5Q',
    appId: '1:955871740032:ios:47cd0d76ca4e59c464a665',
    messagingSenderId: '955871740032',
    projectId: 'drawer-57cde',
    databaseURL: 'https://drawer-57cde-default-rtdb.firebaseio.com',
    storageBucket: 'drawer-57cde.appspot.com',
    iosBundleId: 'com.example.smartGrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr1aA2BEAJ0QBmLbjqtZXTKYa0B9-GKlA',
    appId: '1:955871740032:web:ef3ded4c640e476464a665',
    messagingSenderId: '955871740032',
    projectId: 'drawer-57cde',
    authDomain: 'drawer-57cde.firebaseapp.com',
    databaseURL: 'https://drawer-57cde-default-rtdb.firebaseio.com',
    storageBucket: 'drawer-57cde.appspot.com',
    measurementId: 'G-9S3NXX2Z2J',
  );

}